// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq0UfUs8nRXSoRJxaT76Ij577czuVqPlw',
    appId: '1:113285381450:web:7e98f81762fd21ecc195b3',
    messagingSenderId: '113285381450',
    projectId: 'test-66a11',
    authDomain: 'test-66a11.firebaseapp.com',
    databaseURL: 'https://test-66a11-default-rtdb.firebaseio.com',
    storageBucket: 'test-66a11.firebasestorage.app',
    measurementId: 'G-MVH9DCSLGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmATvtHNzzOD0QgzfNhm0HhvhBP5xXq4',
    appId: '1:113285381450:android:0e92982bc1061a37c195b3',
    messagingSenderId: '113285381450',
    projectId: 'test-66a11',
    databaseURL: 'https://test-66a11-default-rtdb.firebaseio.com',
    storageBucket: 'test-66a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvsi6PJrON_5M0-aBcpIRxpGNymiwDtV4',
    appId: '1:113285381450:ios:6a0d23561a06b5e3c195b3',
    messagingSenderId: '113285381450',
    projectId: 'test-66a11',
    databaseURL: 'https://test-66a11-default-rtdb.firebaseio.com',
    storageBucket: 'test-66a11.firebasestorage.app',
    androidClientId: '113285381450-2maenn43b3hjhpurd3dup3mtufspe58l.apps.googleusercontent.com',
    iosClientId: '113285381450-p2o3eb1b482pr53l2drvm72llto9pj3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvsi6PJrON_5M0-aBcpIRxpGNymiwDtV4',
    appId: '1:113285381450:ios:6a0d23561a06b5e3c195b3',
    messagingSenderId: '113285381450',
    projectId: 'test-66a11',
    databaseURL: 'https://test-66a11-default-rtdb.firebaseio.com',
    storageBucket: 'test-66a11.firebasestorage.app',
    androidClientId: '113285381450-2maenn43b3hjhpurd3dup3mtufspe58l.apps.googleusercontent.com',
    iosClientId: '113285381450-p2o3eb1b482pr53l2drvm72llto9pj3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq0UfUs8nRXSoRJxaT76Ij577czuVqPlw',
    appId: '1:113285381450:web:ddb97d2f05dd8c62c195b3',
    messagingSenderId: '113285381450',
    projectId: 'test-66a11',
    authDomain: 'test-66a11.firebaseapp.com',
    databaseURL: 'https://test-66a11-default-rtdb.firebaseio.com',
    storageBucket: 'test-66a11.firebasestorage.app',
    measurementId: 'G-CEWRYED40C',
  );

}